[Icon Theme]
Name=Papirus

DesktopDefault=24
ToolbarDefault=24
ToolbarSizes=24
MainToolbarDefault=24
MainToolbarSizes=24
PanelDefault=24
PanelSizes=24
FollowsColorScheme=true

# Directory list
Directories=actions,devices,mimetypes,places,status

[actions]
Context=Actions
Size=24
Type=Fixed

[devices]
Context=Devices
Size=24
Type=Fixed

[mimetypes]
Context=MimeTypes
Size=24
Type=Fixed

[places]
Context=Places
Size=24
Type=Fixed

[status]
Context=Status
Size=24
Type=Fixed